# helm install prometheus prometheus-community/kube-prometheus-stack \
# --namespace monitoring \
# --create-namespace \
# -f values.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ingress.yaml
  #  - login-secret.yaml
  - pve-dashboard.yaml
