apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-ui-ingress-certificate
  namespace: longhorn-system
spec:
  secretName: longhorn-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - longhorn.home.jonahsserver.com
