apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: gpu-operator
      version: "v25.3.3"
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
  values:
    driver:
      enabled: false
    containerd:
      config: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
      socket: /run/k3s/containerd/containerd.sock
      runtimeClassName: "nvidia"
      setAsDefault: true
    cdi:
      enabled: true
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
    validator:
      runtimeClassName: "nvidia"
