apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rancher.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: rancher
          namespace: cattle-system
          port: 80
  tls:
    secretName: rancher-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-ingress-certificate
spec:
  secretName: rancher-tls-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - rancher.home.jonahsserver.com
