apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
spec:
  interval: 15m
  chart:
    spec:
      chart: rancher
      version: "2.12.0"
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
      interval: 5m
  values:
    hostname: rancher.home.jonahsserver.com
    ingress:
      enabled: true
      ingressClassName: traefik
      extraAnnotations:
        cert-manager.io/cluster-issuer: "cloudflare-issuer"
    tls: external
    bootstrapPassword: null
