apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rancher-bootstrap-secret
  namespace: cattle-system
spec:
  encryptedData:
    password: AgDIJdvzaplKnTpxB6QQMh8RWM3DI/EngQ5759SuH96pEsifFQ5TMQatL0X169iY00qy1KrLStiFjDrO1vfys3pYXRjTl0nAqJZQ1mGtjsivcilrl38yJWz/9n1tjdLLyznRz2Oe6PORn74GZcQgIZUDfvHnjgsHwk0h3KUivngsU3b5sEa7pU708e+gYfrOVcolMvhewrJ/GALd3kU4FT7/wiY/iFdQeSjwg5rFeZne243mF2wXW0EV+XWsLktPZM1KZv5bbBKcM0iL5NUpRMNL6A9Ff0GKnZHUxQjf28cE7l/yZj8+8L51sY7PpF7R9bndjsWjwQAQO39RuVjwCBHXuMmODzmSePNQy8rEB92b0kR3Nxs7nCZpz2R09NLBJjBsgMhHl4gFgQngt8rZx2lEQCZByywkMOO62T6Hc8oYJFqvpassumwOcty6QJWtNrTmDCZo9IydUNtvrXKwbxIVwipqD5TSlsvtHNQsBfCXAaSOWdEBx9B/RfrRdYwPyaczze1WtLZFUVlpZcgicajtNMU/cjfQhSFUojiIfYIBxhftZ6pR0DUC8bfjdlMvzorK3vh6yr+ItXa7UZ1n9qtImn8MLsTNyKgGFSk0sdkEANoWehxaOPmwiqGGQfvf4zoHNBt0hw7L8nrPrpYJ/1Bc9i/asrbdQB5sB+Ar9waLO/TY8AIJinWBFewweczPqhMeHCDE+RsoiAP3wh2d8HI=
  template:
    metadata:
      name: rancher-bootstrap-secret
      namespace: cattle-system
