apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: exporter-has
  labels:
    release: prometheus
spec:
  staticConfigs:
    - targets:
        - 192.168.4.52:9100
  metricsPath: /metrics
