apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
spec:
  interval: 30m
  url: https://bitnami-labs.github.io/sealed-secrets
# Seal a Secret
# kubeseal --controller-name sealed-secrets --controller-namespace kube-system --format yaml < unsealed-secret.yaml > sealed-secret.yaml
