apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-ui-ingress-certificate
  namespace: wazuh
spec:
  secretName: wazuh-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - wazuh.home.jonahsserver.com
