apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgDGhSvD/Bkg8/sx6W+OsJQTVuh7OpbpNhC6eDKwXYHouZqJW8oORCMUy7kX7FqKfKfiEQTn5sGuvbxFCZGk3R7Ers4+5QKRRqk3JzgFo3kNYRNLzyuxMJv0b2EwFSZh1VBY/qbUMQ7a2p4p5B0pFOEOGQAKkYyRRMvDl3+dDzNoiaSPu/tfY2KUrR+5fobDPrx8MxxvQz2lrXzd+BaJft9KoAnkt4Z7kgd/qprweL4PxH3cIeLbVhLvxaIJKsgi4kO06lBC4nDNBUQjiuRswFCv1qaGeNzUHzzWKUzmMRFTFmvzTNP4JlJ+jilD5xJK6NFWwOfZETzV3Q/9q5W/pqDA4rLqXIY7IGSzcB0TWSCnKRSBGe93Yf9ZWSvuo9jj3q9Ma8+qyNw4dYSS9JBdGKl8w1rMN1/t78BEB1RZvp/u9654bssjUCECTe2cT1A6SrbYPfOAHNt9I4/RQFTuzliLRAIH+jzRG9KgKnnzZb9b/oGfczkYXU8wlDZ1ELPQUlqBKlZ11RJrypVExnNavctZCuIN0ULg5jCU3mTEIF+Wrajg5J66h4ao2bluuyRQWh1gv/Id8BStgjidL/5FEkAUu9F2mBsH/tD3wur2+DmCGxdnKhWYu0dc3b+W28Og+BA/3U0OQ9kzvUJYI7EoLBzqoVjNgjSyo1NzCb2N7f7uWRppV29fBn55NJnJkrVwLn1blV9T/7uBc7MaH+RXRfU=
  template:
    metadata:
      name: pihole-secret
      namespace: pihole
    type: Opaque
