apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  labels:
    app: searxng
data:
  settings.yml: |
    use_default_settings: true

    search:
      default_lang: en-US
      formats:
        - html
        - json

    server:
      limiter: false
      public_instance: false
      method: GET

    outgoing:
      request_timeout: 3.0
      max_request_timeout: 5.0
      pool_connections: 30
      pool_maxsize: 20
      enable_http2: true
