apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: searxng/searxng:2026.8.29-d226b78bc@sha256:b36af7984b87191b595bc5301418ed6432c047668a4547ab531a7439b816fac3
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SEARXNG_BASE_URL
              value: "http://searxng.oswald-ai.svc.cluster.local:8080/"
            - name: SEARXNG_PORT
              value: "8080"
            - name: SEARXNG_SECRET
              valueFrom:
                secretKeyRef:
                  name: searxng-secret
                  key: SEARXNG_SECRET

          volumeMounts:
            - name: config-volume
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml

      volumes:
        - name: config-volume
          configMap:
            name: searxng-config
