---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: oswald-ai
spec:
  encryptedData:
    SEARXNG_SECRET: AgDMSOh52EZeqZVw6MqDkFz8ravJknF4Sn805ouRwfXr+6spgK/8hR4bJT2wd7WNC1A9eje36iEWoRVLJUm87i2L5Kswy7pRkKqpXvzZvy9wPFDOM25NTmbDExTH9k65hLGd++EIY3oLwGkuuInTvOU+Uei18iN8VHRmMpqBXJmSV9+X+fBGT2+9QHzUkUuEBwVC29pLutkUDHr8N5gr0m5nwBIE89JUjAKa7ox4Ul2z55LuW9bSv2tUtGSxwIAybFbOA8hukO6QyTqR9wMls6rSO4GM5IAUqC6CTLiFTELrA+XyhSUI4h2ziJtvDpZWq1V+kBmnHr1dKJHmJIygyGsyzPyDAzq1xxAS0qgJsRDz1g5wzdsxnOGPacmkGhXLFr0tpE6d69YnO11auRSaT8rBVCeYSWLn5aKSnXQGKvXm65COfP+9hclsalPUru+OpjvVV/9t833evfvW7fxY78xF7D7iGqso6qh4YNFU6oIYjhsZUgw6Z3Pk940DvA2mnQ61lUgmJO5R46bNAgIjJcMpfBDL3pvdj65tcEh+AT8kDi6j9Bn+jF3+URAxIF9gwGpByc4nulyVeEOyfsHyu49R6/wyoWy8/MSFAQvpbAWQraZZ08x4CNtce7PFolPzv0dAfm+KVLAvBhNFqB5I9/KUDYpTKjJqp6B5GUw7/QszvONxugTafj7xqBIkm+V0VH4Lb2sOQKXQNXo0XeYeJ4AzcqhJYI17Z+q+zMScgmhs7IC0H1cju49wzkLw6chhCOJR62LvnXm//hG/O8hJqGIX
  template:
    metadata:
      name: searxng-secret
      namespace: oswald-ai
