# helm install cert-manager jetstack/cert-manager \
# --namespace cert-manager \
# --create-namespace \
# -f values.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  #  - api-secret.yaml
  - cert-issuer.yaml
