apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  encryptedData:
    api-token: AgCF63860qlHTNjQZZ1bjfd6c/lUgVp1WhXrKM/oAmiiRmKSwAnui2EuEea7/6/RG+ymMUExxU9GVMSUvTiGcw39esWa3FL+DHwMt4vMMouZA3kagFLpZky7jQmL/1MQsT5uTZ1lPAYdFVoWsLiWCWEgD9LrYiqpsVKN3Qnt18gDxCDyTr2qNA26IaMtQ1grU2Y8lDLHJYft5/PufTuON4jhoRjMCv+KnaVmTU9Sx38U9uEMzURHO7IujqnCWQ/UHzFr4OG6DRaf9yc066IvrbiyqJZXyeSlKn/T6QHhEromC8PGjfOBUu1EF/GUA9vAdegmhY8e4uRwArRgF4QhaYSsbVgZuKZD6tyKPxYjkPhBEBi0jvb1BvEWlzXJWuU/nYjeE+Lg7VBdi4HUOLx5B5zXXxfGQrOUeZW9qmZ+4Cf1XHiQQHFo1Hx6QRO+zRTxHBiZ03IzPjK+rFTbir66Ri+/lhdwdm6hBVG7EWhykp5Pzi3aEpyVffwWrmivLcnonZEHN1oqFPzO9qFebkKNYDBZ5OJN8Ur7Y7wG073h76mB1l/qX/apM1XlkgCk92LiXo4GYtAOk8yFrKfnISRm2YOyhkGXmQRlr5eFCyGXfEUZqOWcTEs0OYnVtV7M5fSjSkV1cGFTxvOl9WjAbzuTJdLDoz9/+oQ0bdGsl8pFJg5/vqnRKHeTZ+53LGuHKlCHusenZLPpi0NTpUbn9ZIIVyx2i84toAlemeFSGXqLmsuXgVXjZnSxNSSU
  template:
    metadata:
      name: cloudflare-api-token-secret
    type: Opaque
