apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDIrO/L3H+HqEiTmPah6mgSezFmRUzAvgul6Sq66fBWJAy5QTEEg3lQ0MOvHpZUJYw1EV+wMjfr6aIsQ3n1Bh7Sz9Wy5OYBjbpUdspfuvBik/eTDo69p2gKPRcsWVvENTvdqUzS7skJin1DJtIrZN2yXVmpnuRawTTbmq3pJ4G6guC3Kg9JzS1tWcBgIvIEYchZ6StwsbkSBVxd7sV64HzgeIegjl2hAGpOlHDUWc2wU4FM90lpb0t5TGrGusYle9+bV6YGZQcaKWyEPyt+UHcQwNyBNyR2RCXFLvkPDg+iZ5kiTupsSweJQoZnHsoBxfwik5pQZyaXMRN5nhPwlcawEFLqkQBa35MV6c22WzqfKqQH4WtmSVR1jcIt7jURpF43VGjmqLtch8ABLOc47kps0h/OMb5SBYlBRaBzAbdqfWNLDNfXyo7MFMTD65JeyHh+uEhoSkI0WMe6X197l//aaMzlxDztQ5siMNMGyjW39RO1LDlHv4pgMUIf1QZI55TqTBrdcVW7tvLwsWWlKBp3tLbD8NV90fW4Euv0jDhI72PwEM6NSzv5xpVPGYm1fu6aq+daiW+9RsV3wHKeSN8e041jRw8LUF+quqFzYMhAEFPlxIsrXAX3Q4VcfkVnBB2odfkFOqS9/66zs38LvlaepNUrWWSIJecMvd0uv30Nwbkckk0A1zl7hTe5s+CQxBnO1YLdzLdFdCDLH+LsjF4Y3ZLldoJ+rwj0nBm/wAnh4AApfuCoUzRO
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
