apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA25r1Y6/IN4bMX5kqCDuak6RsQtK5whPgbjemt0F6pE+XNS5VIj2jWXNGCIT+eLC6T6Zd8jlxYNRwSIlx8bvdGY03SH8aN88dMH9rRtt3ifCQyRy2itmS36sm1Zu5eYsoPJEVYxF1KKnT1jv1YIxNy7UAAwAcjvZUuKTi2SeBroJqFaTyPukBCKSgGA0THQx7+IOt9+ow2R9eeOlfGpUBliwwKDtZswVUN4RoFaIdFvXOVLG9pNKoap4X9BWsOZAwsS3N6kjvixYqB+q4wKXiHgLw2l+4QY4v6X5M3BOhnOO4RszZzZDRx3WuwhgeGChawo78WW1tx43tGWcjGS+tQO0PPow70rLsY8DVpShsqaDwFwVVvpRmNXyP6qBs9bNztkjiaeBaNjcv7wYvJUIc9PsSIJq9SzUqVCgjox6urOjpPdurlen+CD/Rtcj1P65VnXkZ2Js/blMiApNfzkIv42ndtqZVGCsXmpeMWHwt8B1+U7/TWl/3ktoRFND+xr3OjBXXTJcaU1uYkufFSK1wxwIDEO8i3/nLigSwso7vGbU9lqAp+lgKZlgqNFdkah0hhPOWnYKzpG7fAWgRY5/U0sFPj+WQ7U6VnZxB/eq9w7Z6dyuALiUSkK4BxKuyIyX+Ku61XqWsqOvb4198tCB8X8ZBW3d8Vf2Xk/B8EBltosuMwnYVeAdpGtfrvlHVhXuFCI+VaXt5154Zt/UcUWFrHqn5+ChhDPX0quDkJOFJ7xDfLQYJvHkQ8
  template:
    metadata:
      name: cloudflare-api-token-secret
    type: Opaque
