apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - namespace.yaml
  - helm-repo.yaml
  - sealed-ui-password.yaml
  - volume.yaml
  - release.yaml
  - ingress.yaml
