apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: LoadBalancer
  selector:
    name: ollama
  ports:
    - port: 11434
      name: http
      targetPort: http
      protocol: TCP
