apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alertmanager-rules
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: oswald.rules
      rules:
        - alert: ProxmoxGuestDown
          expr: |
            pve_up{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"} == 0
            and on (id, instance) group_left(name, type)
            pve_guest_info{instance="exporter-proxmox.monitoring.svc.cluster.local:9221", template!="1"}

          for: 5m

          labels:
            severity: critical

          annotations:
            summary: "Proxmox guest {{ $labels.name }} is down"
            description: "The Proxmox {{ $labels.type }} '{{ $labels.name }}' (ID: {{ $labels.id }}) is not running."
