apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: has-webhook-config
  labels:
    alertmanagerConfig: "main"
spec:
  route:
    receiver: "has-webhook-receiver"
    match_not:
      - alertname: "Watchdog"
    groupBy:
      - alertname
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes: []

  receivers:
    - name: "has-webhook-receiver"
      webhookConfigs:
        - urlSecret:
            name: contactpoint-has-webhook
            key: webhook_url
          httpConfig:
            bearerTokenSecret:
              name: contactpoint-has-webhook
              key: auth_header
          sendResolved: true
