apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helm-repo.yaml
  - sealed-ui-creds.yaml
  - sealed-has-webhook.yaml
  - release.yaml
  - pve-dashboard.yaml
  - has-dashboard.yaml
  - alertmanager.yaml
  - ingress.yaml
