apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: proxmox-general
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: proxmox.rules
      rules:
        # Notifies me if a proxmox lxc/vm is down for >5 mins
        - alert: ProxmoxGuestDown
          expr: |
            (
              pve_up{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
              * on (id, instance) group_left(name, type)
              pve_guest_info{instance="exporter-proxmox.monitoring.svc.cluster.local:9221", template!="1"}
            ) == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Proxmox guest {{ $labels.name }} is down"
            description: "The Proxmox {{ $labels.type }} '{{ $labels.name }}' (ID: {{ $labels.id }}) is not running."

        # Notifies if Host CPU usage is >75% for 10mins
        - alert: ProxmoxHostCpuHigh
          expr: |
            (
              pve_cpu_usage_ratio{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
              * on (id, instance) group_left(name)
              pve_node_info{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
            ) > 0.75
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Proxmox host {{ $labels.name }} CPU usage high"
            description: "Host '{{ $labels.name }}' (ID: {{ $labels.id }}) has a CPU usage of {{ $value | humanizePercentage }}."

        # Notifies if Host disk usage is >75% for 5mins
        - alert: ProxmoxHostStorageHigh
          expr: |
            (
              (
                pve_disk_usage_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221", id=~"storage/.+"}
                /
                pve_disk_size_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221", id=~"storage/.+"}
              )
              * on (id, instance) group_left(storage)
              pve_storage_info{instance="exporter-proxmox.monitoring.svc.cluster.local:9221", storage!="local"}
            ) > 0.75
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Proxmox storage {{ $labels.storage }} usage high"
            description: "The Proxmox storage pool '{{ $labels.storage }}' (ID: {{ $labels.id }}) has disk usage of {{ $value | humanizePercentage }} (Threshold: 80%)."

        # Notifies if Host RAM usage is >75% for 10mins
        - alert: ProxmoxHostMemoryHigh
          expr: |
            (
              (
                pve_memory_usage_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
                /
                pve_memory_size_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
              )
              * on (id, instance) group_left(name)
              pve_node_info{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
            ) > 0.75
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Proxmox host {{ $labels.name }} memory usage high"
            description: "Host '{{ $labels.name }}' (ID: {{ $labels.id }}) has a memory usage of {{ $value | humanizePercentage }}."

        # Notifies if Guest CPU usage is >75% for 10mins
        - alert: ProxmoxGuestCpuHigh
          expr: |
            (
              (
                (
                  pve_cpu_usage_ratio{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
                  /
                  pve_cpu_usage_limit{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
                )
                * on (id, instance) group_left(name, type)
                pve_guest_info{instance="exporter-proxmox.monitoring.svc.cluster.local:9221", template!="1"}
              )
              and on (id, instance)
              (pve_up{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"} == 1)
            ) > 0.75
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Proxmox guest {{ $labels.name }} CPU usage high"
            description: "The Proxmox {{ $labels.type }} '{{ $labels.name }}' (ID: {{ $labels.id }}) has a CPU usage of {{ $value | humanizePercentage }}."

        # Notifies if LXC RAM usage is >75% for 10mins
        - alert: ProxmoxLxcGuestMemoryHigh
          expr: |
            (
              (
                (
                  pve_memory_usage_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
                  /
                  pve_memory_size_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
                )
                * on (id, instance) group_left(name, type)
                pve_guest_info{instance="exporter-proxmox.monitoring.svc.cluster.local:9221", template!="1", type="lxc"}
              )
              and on (id, instance)
              (pve_up{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"} == 1)
            ) > 0.75
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Proxmox LXC {{ $labels.name }} memory usage high"
            description: "The Proxmox LXC '{{ $labels.name }}' (ID: {{ $labels.id }}) has memory usage of {{ $value | humanizePercentage }} (Threshold: 75%)."

        # Notifies if VM RAM usage is >90% for 10mins
        - alert: ProxmoxVmGuestMemoryHigh
          expr: |
            (
              (
                (
                  pve_memory_usage_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
                  /
                  pve_memory_size_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
                )
                * on (id, instance) group_left(name, type)
                pve_guest_info{instance="exporter-proxmox.monitoring.svc.cluster.local:9221", template!="1", type="qemu"}
              )
              and on (id, instance)
              (pve_up{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"} == 1)
            ) > 0.90
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Proxmox VM {{ $labels.name }} memory usage high"
            description: "The Proxmox VM (QEMU) '{{ $labels.name }}' (ID: {{ $labels.id }}) has memory usage of {{ $value | humanizePercentage }} (Threshold: 90%)."

        # Notifies if LXC disk usage is >75% for 5mins
        - alert: ProxmoxLxcGuestDiskHigh
          expr: |
            (
              (
                (
                  pve_disk_usage_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
                  /
                  pve_disk_size_bytes{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"}
                )
                * on (id, instance) group_left(name, type)
                pve_guest_info{instance="exporter-proxmox.monitoring.svc.cluster.local:9221", template!="1", type="lxc"}
              )
              and on (id, instance)
              (pve_up{instance="exporter-proxmox.monitoring.svc.cluster.local:9221"} == 1)
            ) > 0.75
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Proxmox LXC {{ $labels.name }} disk usage high"
            description: "The Proxmox LXC '{{ $labels.name }}' (ID: {{ $labels.id }}) has disk usage of {{ $value | humanizePercentage }} (Threshold: 75%)."
