apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: "75.9.0"
  values:
    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: admin_user
        passwordKey: admin_password
      # It's best practice to null out the plaintext values to ensure they are not used.
      adminUser: ""
      adminPassword: ""

      extraSecretMounts:
        - name: grafana-has-webhook-mount
          secretName: contactpoint-has-webhook
          mountPath: /etc/grafana/secrets/has-webhook
          readOnly: true

      alerting:
        contactPoints:
          - orgId: 1
            name: "home-assistant-webhook"
            receivers:
              - uid: "grafana-has-webhook-uid-v1"
                type: "webhook"
                settings:
                  url: $__file{/etc/grafana/secrets/has-webhook/webhook_url}
                  httpMethod: "POST"
                secureSettings:
                  httpHeader:
                    Authorization: $__file{/etc/grafana/secrets/has-webhook/auth_header}

        notificationPolicies:
          - orgId: 1
            receiver: "home-assistant-webhook"
            group_by: ["grafana_folder", "alertname"]

    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: "has-exporter"
            static_configs:
              - targets: ["192.168.4.52:9100"]
          - job_name: "proxmox-exporter"
            metrics_path: /pve
            params:
              target: ["192.168.4.73"]
            static_configs:
              - targets: ["exporter-proxmox.monitoring.svc.cluster.local:9221"]
