apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: "75.9.0"
  values:
    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: admin_user
        passwordKey: admin_password
      # It's best practice to null out the plaintext values to ensure they are not used.
      adminUser: ""
      adminPassword: ""

      extraSecretMounts:
        - name: has-webhook-secret-files
          mountPath: /etc/grafana/secrets/has-webhook
          secretName: contactpoint-has-webhook
          readOnly: true

      alerting:
        policies.yaml:
          apiVersion: 1
          policies:
            - orgId: 1
              receiver: home-assistant
              group_by:
                - grafana_folder
                - alertname
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 4h
        contactpoints.yaml:
          secret:
            apiVersion: 1
            contactPoints:
              - orgId: 1
                name: home-assistant
                receivers:
                  - uid: df2czb4mzd728f
                    type: webhook
                    settings:
                      authorization_credentials: $__file{/etc/grafana/secrets/has-webhook/auth_header}
                      httpMethod: POST
                      url: $__file{/etc/grafana/secrets/has-webhook/webhook_url}
                    disableResolveMessage: false

    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: "has-exporter"
            static_configs:
              - targets: ["192.168.4.52:9100"]
          - job_name: "proxmox-exporter"
            metrics_path: /pve
            params:
              target: ["192.168.4.73"]
            static_configs:
              - targets: ["exporter-proxmox.monitoring.svc.cluster.local:9221"]
