apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: "75.9.0"
  values:
    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: admin_user
        passwordKey: admin_password
      # It's best practice to null out the plaintext values to ensure they are not used.
      adminUser: ""
      adminPassword: ""

    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: "has-exporter"
            static_configs:
              - targets: ["192.168.4.52:9100"]
          - job_name: "proxmox-exporter"
            metrics_path: /pve
            params:
              target: ["192.168.4.73"]
            static_configs:
              - targets: ["exporter-proxmox.monitoring.svc.cluster.local:9221"]

    alertmanager:
      extraSecrets:
        - contactpoint-has-webhook

      config:
        global:
          resolve_timeout: 5m

        route:
          receiver: "monitoring/has-webhook-config/has-webhook-receiver"
          group_by: ["alertname"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h

          routes:
            - receiver: "null"
              matchers:
                - alertname="Watchdog"

        receivers:
          - name: "null"

          - name: "has-webhook-receiver"
            webhook_configs:
              - url_file: /etc/alertmanager/secrets/contactpoint-has-webhook/webhook_url
                http_config:
                  bearer_token_file: /etc/alertmanager/secrets/contactpoint-has-webhook/auth_header
                send_resolved: true
