apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-has-webhook
  namespace: monitoring
spec:
  encryptedData:
    has_webhook_url: AgBX1XhPnDPOQFslB1x50IYiIwMSs25TqWTsZGuQijDAoBVL4U/wkTrWAlpuKaaw5XQUF0ZbOiRFxykCBXUqF3LMMQD+iqauoM5W5MZ6/qso7PT7NHOYtwhPUk5K5IORLZz55IfKLBAPKYW9He4+aqUpJNzTv6Dm+6+Zm6WN2zk4Q0mU5HsyxlC6Ib+T3FaNlCe4TfmMj9JmHiRYwS3hu3eDjSaybih0BqNRjak5003yVmhiBuuXIOLODHOIoHKTrfIDnrQvqsTs8O5DoxZhXNbDJgIyB9C3aM16n1voArJykZDR9xbRKESUPGoogBMU01DlGCFi9Jkzt3lkS7S4+VlZ7700d2hzJFWu7hO1vvYtoAQ9pzvyFJi2tAnScH0AS+3CktpvfTGRkD5KOwoF0+/MgMc9t0iwWcJz/8ISRVrOGyU6Bve5kaqlKYWSPzncMoPSXyUiN13ohKYdKOnurkxoXfRe9lOyUTdyQxKylgeWCtxX219op7no/Py/lO1goV1Xw+2WzJ/jvJ+xJjW3P8b6n5tvUEAeT/WJNtWbtSerrd58kb99NWtOpPlcGX2NA/+SY68M2YPOr7UkntXEtteo/0ykLtDeXusE1ZToX5DG+jlBYLHRc3kPbWWfA2oMylM87Qw69Wv+dOx25eD9hTbwmyhODZ24hdn8jYsHzSOpvpf2nJXMUPlHqUUrmXY65nvDXfSoDV4E6hKOhU+onXFRGpjLVmRukqujeQSaw+k15l5xvjYyxST/2Vzc9x7J6Si80w9oQm6vRQNDgvEAObwKAFarhLc7vdns0qjYjmOBmdAjZNcO/1ACjD0toI5ezOvcSC7sMpknnmxRKQxYshoNb5XHFffIEYvwqPruixNC8yXd5t/iHGnypA6Fb3iT59gsh2Uk4s1XXDbdAVGDypd8fxPFlle55jrvpuxjAD2UaEGme6Ebr33AAyycgGWsBWflDKd/czwf4/B5+xQDZAPOAVaPFZ1SweK5hh0PUw==
  template:
    metadata:
      name: alertmanager-has-webhook
      namespace: monitoring
    type: Opaque
