apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin_password: AgBqZijPhlUFpx8Za/IgurTfj2dnfdYbrYgx3+1+Ati20m/8ukhCC3ENZ4+o4oiy2ChGlyEiHvCYq1UkljEY4B7/dTUvnZcy6InEsfzsdwB9vRv5eYSi/X+JNWeJFP+CDKJY+rq+NfJ/ksaqrx75lKLYaqJanEBYsB4FePYGa5HX+tTJxzMc8cadtVgiKjLKSRIxgmVA/wuRA5K4iuQM/vWl4sLJ+H1UZgDYBKgeZ6TYQm8PQm9aD6J9uFCHx7WyqWGRnEx33ZDNUVOWupE1hZp5UBIZ11fK8uNggmYRsbjuCxT+gCsYP6s/ScDRmtlpDm+arTxpq0294WGwvBOJKVND7TSbapD+0o8jolof7mYXF43QJLAqMqK8OBBY2nAtRB/Vtpayl4EFkOTfr+9k/R4WOQJIQzNtvLfGkK1l1ygnQHw0FQTdmgCy0qJeufHdYT7c0PX7GC4SSmStDp37ap7SZbqv4UxW0Z0rk4ejuiasM27J5EBsp56QBFLldJD6yvNuJhI8W9GyDkw+e5T8kkG6VJsfWBMs85MXMBqckKCnOkdwpF9ETY1KqYm9kvgm5jhE9nm1W27kI5x/UMwR+DZRsHxP3q2DncXh6HUbPWBHUGWXwu2RodghvnS+FEMvsR8Dy43VY4kCZA4Oq4u0LYJLGzsSdmDBhyaC74AR3k3IZibAzJf+bufb9b7WdeeZ3XspQBux7mwVz/suyfDfDw==
    admin_user: AgA35XGxVxU0l3iFK1NQ+ob2EKzrOENM/W+04+6r6qPiCOVCFtG8znWJ+X/vcC/wMbpfdLtCtxhHEFUR6VQASG//yX7GosQWA+KmB2cMcZan+R2S0Wli5Nt4yzgS/F5owqkTJNkcxpANUTTwtVNzfFSp2XFAvqyfMyRNGlps3hAE1ljnPmNLvPvjcLPbmJH0xPOczLqQWm10IhwvoD2L4Mhr5ixcPLhjphAgMiGFao2STCOCmnTK2TH6YKPsdSaveLtUyEIB8SH3AMYBZzAVICEnxWIonQ+8IzBrxuq7JUsj8lSqWYGzMPotuQt1PBTeqjw7rSO4pK07KdXbq3VvxGpCfrOAnX/0IUnuwUfavIHGaGYqFh/RHmb3qPKjNO/Bi/laGIONmZ6OBCW6PNZS/ZaD4CTtHgq+Zw3gCNL8tljm7H4hvSSIXgMoF4FHkvC2DDEu9XJrc4Pw3B3mneVEPeTFV8K4g4QrAkGcTPWgfhaGthCZgSCLUBaNYKmhkXXy8Xnf0P8g6JFaOCTc+8wLmi/uayqBXM7FCmzfmLLqJL2jECAqhsTr84QZ7UFtQa2ykFHsIllyqFRgMi/5YK9cdAMTLND4qC0wx5h6GW+bQj8cMOrIrgtnxWqEd/0NNzvJu1IZTp58LWx5HWSVgiv6WqAEdrf/SwalPYJpSfgnUm1m90E4xGLOxIJ7veRJSrD3L0g+QVmXLwDZeR9SjVY=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
