---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-exporter-secret
  namespace: monitoring
spec:
  encryptedData:
    apiKey: AgBwKthIrXzV68M6oYFiwBQBqlgaauo/T2el/7QHSBKuAQT9OsCuK6+2dFhI19AtzCCv+C5I7QkiyvnhSYjA8InSA7r36I6gMh1NKy2ftxvSmKi8WkHRR19nK9R2CBt12n1Gun64LROOzDIR44k5YvEBPZYUWjrxbkRaSsbgR2lv4A7QXtjh3dkn8HDbIQXeRTdI6YaK3ihGettkK4gK4AhN9nCWje50mxH3uCYL23HeCEV8TNtNZrFlP6OpqtkhhrXZ0ze0coeSm96Xl0Y0HrsoUNPtUYJklcBhHa555NCNDkytA5lEUE/DPoSDYXz5EQsxnfUC1T10VSQ/IMVJWJeDRK0Qs1RwHZ8EA+uulT48oH2bQmNp7TKElP1aiQHajaO+Fc1FCjS622/g6dW0/CDamPzrn9q3MnNYAfy/ZaPArBZYvB5BHKRHXgPNE9DvBkFgA1mB3bo0gsRbEAx4PV/L5zVZShYuCey2nGRk2zXxFiR3YBBeBOQShmBAavDsxzA6gvhzLDvuqxohn0ems7yujkyIy1r1+pXKOaWQYRGE5UXku0nX/gxtAv9ZTOmfUBQo6VkF4Ig7IP8eW4Ayl7/Qw/xfAAC73QKT6H0KF34Swlwmkc4MwbPejit2vHWLwJHV8uHPJlX/5k5YEScmVEgPk8OA+nyK997qtZEkEta0b1qOIDV5zoPCfhVdhtPeE7lkPlQMyfNQWgn3AuVy781+niKBqwLydGRm1hRic9jO0aqOjG4rF/5nfGgLa+uU3pHiFfVMk6bXbj/1C9Pr2B+8EBQ=
  template:
    metadata:
      name: truenas-exporter-secret
      namespace: monitoring
    type: Opaque
