---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-exporter-secret
  namespace: monitoring
spec:
  encryptedData:
    apiKey: AgAC7GYrwTOnWVCM+v0jn3DzawZXHNLajp9xZZd+9M14jcFbVVp4m3rctIE3FkFAVHqSiS3aOeUAIYuVCcuWDH6atNZKZvVf7v72HgZp9+vIhbbrvrA0ddk+ST8gOg0RFame0hU70mGEVaioN/5q4t5TFhbcqyotsXs7gZxXshuwOdcahHzNd44T3o/NWxTCsh71YOykfKOzV/J+Doef/VsTDaXL3tucxHmznDfaExarAMEHO4l/725i4oGAtB21hy2tj30fnarfDGr1HZoOzY+YiGWYooeP/4EOT0bH1f7d3sj+RjJEmLnqv4wYgGrHvasaEaphOzMHnnZprhQpL63E9iTZXL4t430D2qoNG1d76hUm82ReROVMTDB2K+Tn8oV0NZ/TRBgPMkaqtm3mXhTNFywFfc0cuk74CaVXz2xDAfUQkFvjIIvMC/RUFB3z048F8809wATdPPBlfMZTFcuFCGR0Z+9NBG3HtwXqkMBJeZe6gNQe6NFmKl+g+1NKPeUYDskUGtkWIBvuloycsY5WI3HwPMuius0Q09GZesASEyzOArCon9wVq9WV/7EeV3ApxcBwzLxs7y8/9son4MIWx+jTcngowM87PwJujLC4eDmhsELyplmzHe2F5YNr4T9tTUq+7gPk1QoSkqWrosXw30ewAXwd7+HQt03ckIv8Q4O7pKje2OWjCj6ea2gofq78QbXpEHkL96ITbzlPbt5VfK+aHE5dR1WnaSz+S+mJOMe+tNAuMR9cgb9TMVhnEa9LFKR2aRdSM+rXb5bQO5P3/Xk=
  template:
    metadata:
      name: truenas-exporter-secret
      namespace: monitoring
    type: Opaque
