# helm install pihole mojo2600/pihole \
# --namespace pihole \
# --create-namespace \
# -f values.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - ingress.yaml
  - login-secret.yaml
  - volume.yaml
