apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate
resources:
  - namespace.yaml
  - sealed-secret.yaml
  - sealed-config-secrets.yaml
  - pv.yaml
  - pvc.yaml
  - release.yaml
