apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-frigate-media
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: frigate-media-pv
    volumeAttributes:
      source: "//192.168.4.110/frigate"
      subdirectory: ""
    nodeStageSecretRef:
      name: frigate-smb-credentials
      namespace: frigate
