apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-frigate-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  volumeName: pv-frigate-media
  resources:
    requests:
      storage: 1Ti
