apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 15m
  chart:
    spec:
      chart: frigate
      version: "7.8.0"
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: flux-system
      interval: 5m
  values:
    service:
      type: LoadBalancer
      port: 5000

    coral:
      enabled: true
      hostPath: /dev/bus/usb

    securityContext:
      privileged: true

    persistence:
      media:
        enabled: true
        existingClaim: pvc-frigate-media

    extraVolumes:
      - name: frigate-config-volume
        secret:
          secretName: frigate-config
          items:
            - key: config.yaml
              path: config.yaml

    extraVolumeMounts:
      - name: frigate-config-volume
        mountPath: /config/config.yaml
        subPath: config.yaml
        readOnly: true

    configMounts:
      - name: frigate-config
        mountPath: /config
        readOnly: true

    nodeSelector:
      coral: "true"
