apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: frigate
spec:
  interval: 15m
  chart:
    spec:
      chart: frigate
      version: "7.8.0"
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: "0.16.1"

    service:
      type: LoadBalancer
      port: 5000

    coral:
      enabled: true
      hostPath: /dev/bus/usb

    securityContext:
      privileged: true

    persistence:
      media:
        enabled: true
        existingClaim: pvc-frigate-media

    nodeSelector:
      coral: "true"

    envFromSecrets:
      - frigate-config-credentials

    config: |-
      ############################################################
      # REMEMBER CONFIG CHANGES WITHIN THE UI ARE NOT PERSISTENT #
      ############################################################

      mqtt:
        host: 192.168.4.52 
        user: mqtt-user
        password: '{FRIGATE_MQTT_PASS}' 

      go2rtc:
        streams:
          doorbell:
            - '{FRIGATE_DOORBELL_RTSP}_main'
          doorbell_sub:
            - '{FRIGATE_DOORBELL_RTSP}_sub'
          patio:
            - '{FRIGATE_PATIO_RTSP}' 
          driveway:
            - '{FRIGATE_DRIVEWAY_RTSP}' 

      cameras:
        ##############
        ## DOORBELL ##
        ##############

        doorbell:
          enabled: true
          ffmpeg:
            output_args:
              record: preset-record-generic-audio-aac
            inputs:
              - path: rtsp://127.0.0.1:8554/doorbell
                roles:
                  - record
              - path: rtsp://127.0.0.1:8554/doorbell_sub
                roles:
                  - detect
          motion:
            mask: 0.321,0.005,0.32,0.06,0.674,0.06,0.673,0.012
          zones:
            detect:
              coordinates: 1,1,1,0,0.633,0,0.715,0.315,0.752,0.317,0.75,0.703,0.208,0.554,0,0.56,0,1
              loitering_time: 0
              inertia: 3
              objects: person

        ###########
        ## PATIO ##
        ###########

        patio:
          enabled: true
          ffmpeg:
            output_args:
              record: preset-record-generic-audio-aac
            inputs:
              - path: rtsp://127.0.0.1:8554/patio
                roles:
                  - detect
                  - record
          motion:
            mask: 0.714,0.009,0.713,0.053,0.982,0.06,0.975,0.014
          zones: {}

        ##############
        ## DRIVEWAY ##
        ##############

        driveway:
          enabled: true
          ffmpeg:
            output_args:
              record: preset-record-generic-audio-aac
            inputs:
              - path: rtsp://127.0.0.1:8554/driveway
                roles:
                  - detect
                  - record
          motion:
            mask: 0.714,0.009,0.713,0.053,0.982,0.06,0.975,0.014
          zones:
            detect:
              coordinates: 0.198,0.571,0,0.538,0,1,1,1,1,0.701
              loitering_time: 0
              inertia: 3
              objects: person

      ###########################
      ## GLOBAL CAMERA CONFIGs ##
      ###########################

      detect:
        enabled: true
        width: 1280
        height: 720

      objects:
        track:
          - person
        filters:
          person:
            threshold: 0.7
            min_score: 0.5
            min_area: 2000

      record:
        enabled: true
        retain:
          days: 2
          mode: all

      snapshots:
        enabled: true
        timestamp: false
        bounding_box: false
        crop: false
        retain:
          default: 1

      detectors:
        coral:
          type: edgetpu
          device: usb

      version: 0.14
