apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ui-ingress-certificate
  namespace: monitoring
spec:
  secretName: grafana-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.home.jonahsserver.com
