apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "75.6.1"
    releaseName: prometheus
    valuesFile: values.yaml
resources:
  - ingress.yaml
  - login-secret.yaml
  - pve-dashboard.yaml
