grafana:
  admin:
    existingSecret: "grafana-admin-credentials"

    userKey: admin_user
    passwordKey: admin_password

  # It's best practice to null out the plaintext values to ensure they are not used.
  adminUser: ""
  adminPassword: ""
