apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Dev & Ops:
        - Github:
            - abbr: GH
              href: https://github.com/
              icon: github.png
        - Docker Hub:
            - abbr: DH
              href: https://hub.docker.com/
              icon: docker.png
        - Helm Charts:
            - abbr: HC
              href: https://artifacthub.io/
              icon: helm.png
  services.yaml: |
    - IoT & Smarthome:
        - Home Assistant:
            icon: home-assistant.png
            href: https://has.jonahsserver.com
        - Homebridge:
            icon: homebridge.png
            href: https://homebridge.home.jonahsserver.com

    - Infrastructure & Data:
        - PVE-1:
            icon: proxmox.png
            href: https://pve-1.home.jonahsserver.com/
        - PVE-2:
            icon: proxmox.png
            href: https://pve-2.home.jonahsserver.com/
        - PVE-3:
            icon: proxmox.png
            href: https://pve-3.home.jonahsserver.com/
        - TrueNAS:
            icon: truenas.png
            href: https://truenas.home.jonahsserver.com/
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.home.jonahsserver.com/

    - Networking:
        - PiHole:
            icon: pi-hole.png
            href: https://pihole.home.jonahsserver.com/
        - NPM:
            icon: nginx-proxy-manager.png
            href: https://npm.home.jonahsserver.com/
        - Wireguard:
            icon: wireguard.png
            href: https://wg.home.jonahsserver.com/

    - Monitoring & Management:
        - Grafana:
            icon: grafana.png
            href: https://grafana.home.jonahsserver.com/
        - Portainer:
            icon: portainer.png
            href: https://portainer.home.jonahsserver.com/
        - Crafty Controller:
            icon: minecraft.png
            href: https://crafty.home.jonahsserver.com/

    - AI:
        - OpenWebUI:
            icon: open-webui.png
            href: https://oswald.home.jonahsserver.com/

    - Security:
        - Authelia:
            icon: authelia.png
            href: https://auth.home.jonahsserver.com/
        - Vaultwarden:
            icon: vaultwarden.png
            href: https://vaultwarden.home.jonahsserver.com/
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
