apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ui-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: prometheus-grafana
          namespace: monitoring
          port: 80
  tls:
    secretName: grafana-certificate-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ui-ingress-certificate
spec:
  secretName: grafana-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.home.jonahsserver.com
