apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - sealed-secret.yaml
  - release.yaml
  - pve-dashboard.yaml
  - has-dashboard.yaml
  - ingress.yaml
