apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin_password: AgCM1V2hsGQUU2I2l9jitWPEYzCM4PHMzOhIAM+anVj+iA6y/009eLYaMpXBoz3yk99e0KPIPjBXq+kOvYH/OS1ZZjpz9JbzibYNwJ8aYes7FJIPkyDWVIqmqZ3qGIPuOzbERj0X+NokPjntTPYTyARpfnaI8f0rL5lGJo9twtuMjFzQ/Vy6faF9rdcrPf4Q5tUpCbXUoMOB3bIOzeKkao2H+j4LRcGeBdrVrycUKSnk3gHnMr0jNuwfEcEc98h29LnYL0r4y7cEoH8m62pNE/1+Az2nLptZ2wgN14nybgzIHqstP30/NI6AGfAqWqzQ9ewN5QVfUxIlU3SUWB6icKa1G6X/4XOFcSQzrkzIMEMidXSDrtI0+1or8KESRza9/Mq5RcJ0IAInvY015EzLpVveE8giJml8x+Qs1CxAlb3x2XjGOl80MqtOx4+FjY0E6bhJRanx7dAqM6wJrJ8JuqjJ0Nb1JT/loP+98vqvabOWhyBj2EnhO7pVROO4f/QLWtqfGpDHPQ6Wx5jQATXazU0vsKS4iI9t7oU5o7k+GU0Pk2iphAAvVBCnNcJl+26yR6wB9/ZSJ5Z3sXkgXoIERiy/jJbBmAA9sPKIiLcwlyCiTWqjdn6b6owupjjNqCyUBKSoaZSNSlmqYNXzb7TvVQALuqCXVCpC1M2clMvUo4sMu4mCISoRYlAURBwsOJHkNGY5n2udoHuYllQ1A6FfVg==
    admin_user: AgDHqcEs7TE/TDtm7MEKGdqZaBFYn+kkN7pYuOZ8KAsHeyMJOhTJZb2RYZRADXCyAQOosN63+YQZiCk1ODkXwZRBcPdyu5hrLN6+SK22ABiDDznXYOLUirEr0XiQx37KZeE5h4VJRiZbeI+ja6RI3zCI4TdW8TtFCKWkqKtVOBUrhMndcNh8SPYgkZgvhIi6wjxWt6VFGOCdcn+ZQTIZZ06gItek7r0/Dtdu9wnt9UFQb8P4g0oePHiI3DbwNf7PlCda5J20NUc/QF4HkI1u3gE1qbZvHpfAB4osG3Iwc55GiM+SUA9XodbTv1hLX+pl2RRxHyldR8wpvej44oY1Q37Kt5OYfkbZMwVbEIzaw2xc7jFdTsUMugDQw5iqyoVk4WIe3TvlLzDY/9udDXdZtRRI37z0UAdAxSt4110gcFR8gbt9LdsrWNKkRunpY9729oB1R0UnNIVfZOR1FduHgKy9U/Byj1tPSIZDF39nXiL9HU9yb0p7Z0aXtGF4Hu86H4bsP5Uz+s5h+tlloFA/K4a6uQzRVyQNo2XXf1b6M5VgbW3n5WkiDWzpn/FrxG6jxYsETm0td9EcbrMGq4r3Q5buGIneeTkO76T9IXpuEQqhLPHSO7aPvgZYPqY78TOEs9PH3vWGSi2BpLj1IhsaGD1IdEo/LVk8Y4e5rqEjzQoJdG57PoRKCQoGMyl3NzuQNmLabzioLeFS6o51hJM=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
