apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      version: "0.34.3"
  values:
    ingress:
      enabled: false

    storage:
      data:
        name: "vaultwarden-data"
        size: "15Gi"
        class: "vaultwarden-storage"
        accessMode: "ReadWriteOnce"

    domain: "https://vaultwarden.home.jonahsserver.com"
