apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-manager-longhorn
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: longhorn.rules
      rules:
        # volume's actual disk space used (not just provisioned) exceeds 90% of its total capacity for 5 minutes.
        - alert: LonghornVolumeActualSpaceUsedWarning
          annotations:
            description:
              The actual space used by Longhorn volume {{$labels.volume}} on {{$labels.node}} is at {{$value}}% capacity for
              more than 5 minutes.
            summary: The actual used space of Longhorn volume is over 90% of the capacity.
          expr: (longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes) * 100 > 90
          for: 5m
          labels:
            issue: The actual used space of Longhorn volume {{$labels.volume}} on {{$labels.node}} is high.
            severity: warning

        # volume's robustness state is reported as 'Fault' (value of 3) for a continuous 5 minutes.
        - alert: LonghornVolumeStatusCritical
          annotations:
            description:
              Longhorn volume {{$labels.volume}} on {{$labels.node}} is Fault for
              more than 2 minutes.
            summary: Longhorn volume {{$labels.volume}} is Fault
          expr: longhorn_volume_robustness == 3
          for: 5m
          labels:
            issue: Longhorn volume {{$labels.volume}} is Fault.
            severity: critical

        # volume's robustness state is reported as 'Degraded' (value of 2) for a continuous 5 minutes
        - alert: LonghornVolumeStatusWarning
          annotations:
            description:
              Longhorn volume {{$labels.volume}} on {{$labels.node}} is Degraded for
              more than 5 minutes.
            summary: Longhorn volume {{$labels.volume}} is Degraded
          expr: longhorn_volume_robustness == 2
          for: 5m
          labels:
            issue: Longhorn volume {{$labels.volume}} is Degraded.
            severity: warning

        # node's total Longhorn storage usage exceeds 70% of its total schedulable storage capacity for 5 minutes
        - alert: LonghornNodeStorageWarning
          annotations:
            description:
              The used storage of node {{$labels.node}} is at {{$value}}% capacity for
              more than 5 minutes.
            summary: The used storage of node is over 70% of the capacity.
          expr: (longhorn_node_storage_usage_bytes / longhorn_node_storage_capacity_bytes) * 100 > 70
          for: 5m
          labels:
            issue: The used storage of node {{$labels.node}} is high.
            severity: warning

        # specific disk's storage usage exceeds 70% of its total capacity for 5 minutes.
        - alert: LonghornDiskStorageWarning
          annotations:
            description:
              The used storage of disk {{$labels.disk}} on node {{$labels.node}} is at {{$value}}% capacity for
              more than 5 minutes.
            summary: The used storage of disk is over 70% of the capacity.
          expr: (longhorn_disk_usage_bytes / longhorn_disk_capacity_bytes) * 100 > 70
          for: 5m
          labels:
            issue: The used storage of disk {{$labels.disk}} on node {{$labels.node}} is high.
            severity: warning

        # 'Ready' Longhorn nodes is less than the total expected number of nodes for a continuous 5 minutes
        - alert: LonghornNodeDown
          annotations:
            description: There are {{$value}} Longhorn nodes which have been offline for more than 5 minutes.
            summary: Longhorn nodes is offline
          expr: (avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition="ready"} == 1) or on() vector(0)) > 0
          for: 5m
          labels:
            issue: There are {{$value}} Longhorn nodes are offline
            severity: critical

        # instance manager's CPU usage is more than 300% (or 3x) of its requested CPU for 5 minutes.
        - alert: LonghornInstanceManagerCPUUsageWarning
          annotations:
            description:
              Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} has CPU Usage / CPU request is {{$value}}% for
              more than 5 minutes.
            summary: Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} has CPU Usage / CPU request is over 300%.
          expr: (longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu) * 100 > 300
          for: 5m
          labels:
            issue: Longhorn instance manager {{$labels.instance_manager}} on {{$labels.node}} consumes 3 times the CPU request.
            severity: warning

        # node's total CPU usage (as seen by Longhorn) exceeds 90% of its total CPU capacity for 5 minutes.
        - alert: LonghornNodeCPUUsageWarning
          annotations:
            description:
              Longhorn node {{$labels.node}} has CPU Usage / CPU capacity is {{$value}}% for
              more than 5 minutes.
            summary: Longhorn node {{$labels.node}} experiences high CPU pressure for more than 5m.
          expr: (longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu) * 100 > 90
          for: 5m
          labels:
            issue: Longhorn node {{$labels.node}} experiences high CPU pressure.
            severity: warning

        # backup is in the failed state
        - alert: LonghornBackupFailed
          annotations:
            summary: "A Longhorn backup has failed."
            description: "The backup '{{$labels.backup}}' for volume '{{$labels.volume}}' has entered an 'Error' (state 4)."
          expr: longhorn_backup_state == 4
          labels:
            severity: critical

        # backup is stuck for 1 hour indiciating a problem
        - alert: LonghornBackupStuck
          annotations:
            summary: "A Longhorn backup is stuck."
            description: "The backup '{{$labels.backup}}' for volume '{{$labels.volume}}' has been 'InProgress' (state 2) for over 1 hour."
          expr: longhorn_backup_state == 2
          for: 1h
          labels:
            severity: warning

        # checks if the time since the last backup is > 24 hours (86400s) also checks that a backup has run at least once (timestamp > 0)
        - alert: LonghornBackupsStale
          annotations:
            summary: "Longhorn backups are not running."
            description: "The last successful backup for volume '{{$labels.volume}}' was over 24 hours ago. Scheduled backups may be failing or misconfigured."
          expr: (time() - longhorn_volume_last_backup_at > 86400) and (longhorn_volume_last_backup_at > 0)
          labels:
            severity: warning

        # alerts if 3 or more backups are in an error state meaning the target is the issue for 5mins
        - alert: LonghornBackupTargetFailure
          annotations:
            summary: "Multiple backups failing, backup target may be down."
            description: "There are {{ $value }} backups in an 'Error' state simultaneously. This may indicate a systemic problem with the backup target (S3/NFS)."
          expr: count(longhorn_backup_state == 4) > 2
          for: 5m
          labels:
            severity: critical
