apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./kube-prom-stack
  - ./loki-alloy
  - ./proxmox
  - ./truenas
  - ./longhorn
  - ./unpoller
  - ./alerts
  - ./dashboards
