apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: homepage-certificate-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-ingress-certificate
spec:
  secretName: homepage-certificate-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - homepage.home.jonahsserver.com
