apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kube-vip-image
  policy:
    semver:
      range: ">0.9.1"
