apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cert-manager-chart
  policy:
    semver:
      range: ">1.15.1"
