apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: unify-slice
  labels:
    kubernetes.io/service-name: unify
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - "192.168.1.1"
    conditions:
      ready: true
