apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frigate-smb-credentials
  namespace: frigate
spec:
  encryptedData:
    password: AgDIrnsQaeb+l/beoPCgusDZURmgFkhL+clm2UmiBD7hN260rw16jSCK8IkcB/fF3UuiXP4PM3WEIIemD1pJqsLeO6/33RXDHXoTjt47FCQDTwv9xnSa3A0xCVuN9sqmtsT26NPXOGWaKvjuV3AAv27wimfmm1dbEgDzmsk1o1aHeQZt04Y/u5nsmlUqxPWUt/x2QgLoN4CgxFi9q3HpVd0eAyTUYTuSyn67WNbZELb/8F5jlY8lBa171nCn6JKwcbx0F9KfGTMilT2Xxg9utJw5o3wyKmrFFuzh1pvBpPHzCSI3eGtZ6qooOk6J1jbvEI11qINIDoeiLpOhXc67qDZkm4j5T+67bAFzqivSk+3xCuWSeFV82n9Pr5ljYoPRLKCjZntWZzjg1CJSxXK4yGhauMFOLiSwoEtZleruzuBLvv5qy/WQi2QIWt1a6mcfk3JEm3M3hUToe9kKkhud9n4xFvlRGq8uYgz0Sft6sDzHFhsKm12xq9WFI8YCwaT37faXaUG+sIujh3dbrThefo3ArtLaJEqD7zQvH9/yc7rWI5GyzOmjnG4ljnvmSCvj456GCF6s4xdOfTkojFkzcyKUqMfR+s+zReWKqtA9d0TuFXj+HOwORNqj3f1R9YRFIsE6Z4jzauvyuEtmVpTR+lzcFkHB4KrdRoNW3ooIMW+GaMIFJs1MZuCFjBaX84LghaMI3n9xrS07lkGNnckDk5c=
    username: AgBpKU1mR0H9Gavxzlwdg82Y8+Gmfcrf29x4556vogot6Pp9hkqZsCNJeWycwJphC2wv3NYHPerbvSNdaiDOtlsFUFpqKIa2ieqJaNCx1YazlphERQd2URga3yZXyGg5PXic8eK1fkaamBvH5M6mvZXJ+haDk9TmHwUuOODHOACN1Cl7zPwIkJrAONAAz6SemcWS1bybK2iCqTjiuEIMsnoNqwaQO1S3wK9dK9D4ZK6urBWP7kX1BukZJPQ7Bq975YvO7LTL7nyDeJkkfeAyI6O+Vhj0uYsfu9BszMVXmjcMbZdLexGj2dZKjP4NfD94mWUC0ANBma0LX0e428KBwZmqObG1a7hVKj6PaR1DgV7nomhtbe0GYX95SlaG6cB5/xiLwmPGoAwyYJ6HHLGxsuY1mhsxQlnuVq6LFuJqUnhYo+//KZF13/lCWAD/6TZX99HN9AG2dsZMniUtiKsdXiZ6UPQ0FtNfti48bxzgkoW4OM4abNyHtNwWVNNgwx8Eu/JoevVxMaMkYc7zZP3FlB+hQmTmf/pVPuowG6Oh4X7UZ/aIExYkt+hvSHXhnjfcxexk69LRN1GkUF5FIxkQMCdEFsA01o5/3omlQSAXCAKqtA61PaMnDmDM255beegs6UCyJ2+VCn5wWyRozbIHE6kYN32Z6qtO1rSkGx0qVKPpv6eNb6wOjsIE1DinqJk0E1EcB6d4Vu9c
  template:
    metadata:
      name: frigate-smb-credentials
      namespace: frigate
    type: Opaque
