name: Debug PR Workflow Trigger

on:
  push:
    branches:
      - flux-staging

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: A simple step to confirm the trigger
        run: echo "The trigger for flux-staging is working correctly!"
