apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: cloudflare-ddns
spec:
  encryptedData:
    api-token: AgDLUP9MXp3KUy1pK78Tcmun+CRHrgPOIna/UbIg7xGvvD4pR3H2rqhju8U1zICvKbj6OMtNe/LCQmnccCNprrbFc8DisPcYRZExcPYg6dTTqNy9QqVNro3vkAWwzVA8IFFZPeQN/+3imUzTQcdD4NR7QdjW/WtxHPjl6C/5N01tf8a/BNaCIs5hMsNVyNbzbMjqZUi+KQKW0YHp3AdSMUTunUb5vUXopN21j0JujzVuX8UgUa40Gr9ud4JGrwpZ55UbZp69PiKtzFhA/6PXyS5AKGCOH4s3uSrdiSEblBtVUiMjpnLlTlGEV7eft3ZQlOX8phAm4YvjYgwEhlvg5VoR8VcCVUruNaqM2yVqeZHnczttpYr9PyJHl4bbTwVOI26FYH9olLlMfK4Obyk4OfFXXUDHsKqnAO1FegcRTu9TVl6Io/WhWHierPxOj0W2bCDMyOmXh+tzJSzCVDel9GJMeOR7VyZPayTr4W/ACVtmtRGppAaGtxI+5EhLXK7UJBTd8Bh0K1qFU2So4eEL1BJLRVOoXL1AqIVMOGDx9GIpsRMZYYuLNUZd0dCyZz0SQbLvl476D0Sh1LhO3DRrFwTHWC8GKM44n/Ha6UPTZ5S9BNA9pu/YDuuepXwXpeVcHi5eir65B+cDQ0qHz0GgWeRqsg8LmS8ApNBU/lXepF99HDu96ESvubqSIQj7QnJ7MyVK6UAKwc5Q/0n1gmg86568XbRHK9Mdyv+smAO4EMiyOTNYRajQ+tn2
    zone: AgCZgZxrtIcNoUfJhESZkNQ7bpm2Xc0s1g9Ol8Mr05JwWjMiPfy0cfhDtzuzmpYZ8jovrZHS40b9btPS0CqcNqXEh/Sjm8MFlSasXeNWHv5r7GVNK+Fd9orf3EzeQR365gyeQMKt7dYj78Be7HojwP/rF9ySTH2WcKkqIGxZ02aouRWr/pHz5M5HTDpjJkCG0PrsGuCGljOnVEcrum4Rayh+8kJMVubZAwfmKNM16l3puIizUGvWyCwAboWHZF97tByoyni3m6fvoB7k17aFqufzd69OEfmq3GhnUTGYXqph8OtyFT0GnhcRde757mCy4oY5JHBkQKOUxNXtGzJc6es1jNRmNxY/abHUBOodXtSADCTdlaRSL5Ce8uDIn62SwTR3fg9Y1Rpc818vcllSM1GmIzFMChNRW4IgpDRZzNIlpA8TlF8YN2ositr7sR0h8Cgc1RXtNMR3oQI1+KHl7hvsChF6zV47X9N48jOw/45dfNgmi0o11t0AgdbWtdJWje4PfGwrdPP+iokif44rHqC6hdiKmmtzv4i9dnaC1V+vSUlYTFFrFQlMbO+xqfWSNQf2YIqf3yiN9o2Je/u0Tr+1MU4r6SIzX/m0/I/kzrW/V4sbAkxsGjphwj7u5LOTRf//Q4XTMe6MdjZqSAzZjoVAC1YuaWvz5bc+a7qmUIxBQxVU4pRJ3N4uYdGyKw5KFW/R/Qu7TtB1W1h6jGz7wjXX
  template:
    metadata:
      name: cloudflare-credentials
      namespace: cloudflare-ddns
    type: Opaque
